### ISSUE TITLE
Bump Node Version to Match Strapi

### ISSUE THREAD

**Issue by jtfairbank** [ComfortablyCoding/strapi-plugin-slugify#115]
Ran into an issue deploying my Strapi App with this plugin on Digital Ocean.  The `strapi` node versions are `>=18.0.0 <=20.x.x` while `strapi-plugin-slugify` specifies `>=14.19.1 <=18.x.x`.  This is set in the `engine.node` field of `package.json`.

**Comment by ComfortablyCoding** [comment]
Thanks for the report, I'll update them to match strapis versions.

**Comment by ComfortablyCoding** [comment]
This should be fixed in the latest release.

**Comment by jtfairbank** [comment]
Awesome, tysm @ComfortablyCoding!! :partying_face:

**Comment by ComfortablyCoding** [comment]
your welcome :)
