### ISSUE TITLE
[bug] Password fields included when use populate with slugify plugin

### ISSUE THREAD

**Issue by ChristherLenander** [ComfortablyCoding/strapi-plugin-slugify#15]
When you use populate with user, these fields are included. They should not be included in the user object.

password
resetPasswordToken
confirmationToken

![password](https://user-images.githubusercontent.com/49711748/155574836-6043703d-998a-453d-82d0-5fffcf24bac9.jpg)

**Comment by ComfortablyCoding** [comment]
Hello @ChristherLenander,

Thank you for reporting this, it will be fixed in the next release.

**Comment by ChristherLenander** [comment]
👍
