### ISSUE TITLE
Localized slug bug?

### ISSUE THREAD

**Issue by Neyunse** [ComfortablyCoding/strapi-plugin-slugify#25]
I note that if I enter the translated slug it does not find it, I think it would be a good idea to include this.

Example: 
`/api/slugify/slugs/article/dogs`

```
{
  "data": {
    "id": 1,
    "attributes":{
      "title": "LIttle dogs",
      "slug": "dogs",
      //....
    }
  }
}

```
Localized Example
`/api/slugify/slugs/article/perros`

```
{
  "data": null,
  "error": { 
    "status": 404, 
    "name": "NotFoundError", 
    "message": "Not Found", 
    "details": {} 
  }
}

```

**Comment by ComfortablyCoding** [comment]
Hello @Neyunse ,

Thank you for the suggestion but I dont see valid use case for this. Strapi CMS already supports localized entries, is their a reason you cannot create a localized entry for this record?

Checking every possible language permutation on the fly could be quite memory intensive.

**Comment by Neyunse** [comment]
> Hello @Neyunse ,
> 
> Thank you for the suggestion but I dont see valid use case for this. Strapi CMS already supports localized entries, is their a reason you cannot create a localized entry for this record?
> 
> Checking every possible language permutation on the fly could be quite memory intensive.

I have localized entries with strapi, but the plugin doesn't detect the localized slug. Maybe this is a bug?

**Comment by ComfortablyCoding** [comment]
For localized content if the locale parameter is not provided it will use the default one.

If you add the locale parameter to the end of the request it should work.

i.e.
`/api/slugify/slugs/article/perros?llocale=es`

**Comment by Neyunse** [comment]
> For localized content if the locale parameter is not provided it will use the default one.
> 
> If you add the locale parameter to the end of the request it should work.
> 
> i.e. `/api/slugify/slugs/article/perros?llocale=es`

Work thanks 👍🏻

**Comment by alexcho267** [comment]
Is there a way to use this pattern to pass the locale in GraphQL?
