### ISSUE TITLE
Duplicated slugs are created

### ISSUE THREAD

**Issue by mrchristophy** [ComfortablyCoding/strapi-plugin-slugify#55]
Hi, 

Just testing this package, and when I set two entries to have the same title the slug is identical for both entries. I tried setting the field as unique which appears have no difference. Is there a setting somewhere to accommodate only unique slugs?

**Comment by ComfortablyCoding** [comment]
Their is no code for ensuring uniqueness for slugs , please see the discussion in #24 for the full discussion. Essentially, if a unique slug is wanted a unique value should be passed.
