### ISSUE TITLE
slug with count

### ISSUE THREAD

**Issue by spenya** [ComfortablyCoding/strapi-plugin-slugify#60]
When I add a slug with count, with references: title, for exemple. it changes the number each time I save the content, any field, so if someone bookmarks it, the link will not work  if I update the content ...

**Comment by ComfortablyCoding** [comment]
Wierd, I believe i did test the case where title is not changed and slug count remained the same. I will need to look into this further.

**Comment by selected-pixel-jameson** [comment]
@ComfortablyCoding I'm having the same issue. This is a pretty significant issue as it makes the plug-in unusable in a production environment.

**Comment by ComfortablyCoding** [comment]
I have not had a chance to look into this yet, my PC died and did not get a new one yet.

**Comment by LiquidITGuy** [comment]
We got the same issues here.
I put my flag to follow this issue

**Comment by sebyoga** [comment]
I have the same issues, some times save the content, title-slug-1, title-slug-2, title-slug-3...

**Comment by selected-pixel-jameson** [comment]
This definitely has something to do with the server caching something. If I test this locally it will keep increasing the count until I restart the server. At that point if I save the model again it will remove the count and start incrementing again until I restart the server.

**Comment by selected-pixel-jameson** [comment]
@ComfortablyCoding Can you please review my pull request?

**Comment by ComfortablyCoding** [comment]
Fix released in v2.2.3

**Comment by Jasonlgrd** [comment]
Hello,

When I add a slug with count, increment working correctly but when i restart local server yarn develop, count is reset to 0...
Is normal ?

Thx

**Comment by ComfortablyCoding** [comment]
See #81
