### ISSUE TITLE
When I use I18N, how should I use Slugify

### ISSUE THREAD

**Issue by NidMo** [ComfortablyCoding/strapi-plugin-slugify#63]
I have content type.

![image](https://user-images.githubusercontent.com/24955673/172017917-2f4bb5d1-6e0a-4daa-8691-baa7b8478565.png)

The slug filed must be unique.But in different language environments, some words are spelled the same.

For example, the spelling of English marketing is the same as that of German marketing. In this case, the slug should be the same, but the rules restrict that the slug can only be a unique value

**Comment by NidMo** [comment]
Slugification
Any time the respective content types have an entity created or updated the slug field defined in the settings will be auto generated based on the provided reference field.

When I input some Thai and Japanese text content, the automatically generated slug is empty. And the slugs I actively input will be overwritten by the automatically generated rules

**Comment by ComfortablyCoding** [comment]
Their is no unique restriction in place for slugs at this time. Two records can have the same slug.

In regards to the different language coming up empty I will need to look into this.

**Comment by NidMo** [comment]
> 
Can I use a button to control whether to automatically generate a slug

**Comment by ComfortablyCoding** [comment]
At the moment no, it's not possible to disable the slugification for a specific record on save due to how the plugin is built. 

It can potentially be added once custom fields are released but we will need to wait and see how those will operate.

**Comment by ComfortablyCoding** [comment]
I am closing this as it seems to me as not something the plugin can handle by itself. I would suggest 2 possible solutions to anyone else having this issue
1. Use an additional reference to make it unique per record and per internationalization (id and/or locale should ensure this)
2. Use a text field over the uid field for the slug to get around the unique constraint.
