### ISSUE TITLE
[slugification] When using Thai and Japanese, the automatically generated slug is empty

### ISSUE THREAD

**Issue by NidMo** [ComfortablyCoding/strapi-plugin-slugify#64]
![image](https://user-images.githubusercontent.com/24955673/172020179-e5507963-eca2-4763-86cd-d46c784eef7d.png)

**Comment by ComfortablyCoding** [comment]
Upon further investiation unfortunately looks like the underlying package (https://github.com/sindresorhus/slugify) does not support these languages.
