### ISSUE TITLE
not working after upgrade strapi 4.6.1

### ISSUE THREAD

**Issue by sal1ner0** [ComfortablyCoding/strapi-plugin-slugify#90]
Hi there, 

Just update strapi to 4.6.1 and plugin to 2.3.2.. and not working anymore. 

Any known issue?

**Comment by ComfortablyCoding** [comment]
None that I am aware of. Can you post what your plugin config is and expand on what you meant by "it is not working"?

**Comment by sal1ner0** [comment]
Hi again, 

I just run some test and i can confirm if you are trying to **rewrite the same field** it no longer does it like it did before

Works properly if the field and references are different.

**Comment by ComfortablyCoding** [comment]
It's possible they changed something in the newest version, I'll have a look.

**Comment by ComfortablyCoding** [comment]
In this case you need to enable the `shouldUpdateSlug` option so it forces an update. Due to the circular reference if this option is not enabled it will skip the slugification as you will always have some content there.
