### ISSUE TITLE
Update yup dependency to 1.1.1

### ISSUE THREAD

**Issue by Dirvann** [ComfortablyCoding/strapi-plugin-slugify#94]
The yup dependency is currently at version 0.32.x which is outdated. 
It should normally be possible to update it to the latest version 1.1.1. 

The reason is that it clashes with other strapi-plugins that use the major version 1.x.x .

**Comment by ComfortablyCoding** [comment]
The versions for peerDependencies are set based on the versions strapi themselves use as that is where they would be coming from. At the moment the version of yup being used by strapi is [`"yup": "^0.32.9"`](https://github.com/search?q=repo%3Astrapi%2Fstrapi+yup+language%3AJSON&type=code&l=JSON).

I do plan on removing these explicit peerDependencies (aside from `@strapi/strapi` as that is required) same as I did for some of my other packages. In doing so these types of issues should resolve themselves.

**Comment by Dirvann** [comment]
Makes sense! Thanks for the info. I suppose the @strapi/strapi should update that dependency first
