### ISSUE TITLE
receiving error 403 when trying to find by slug

### ISSUE THREAD

**Issue by sebackend** [ComfortablyCoding/strapi-plugin-slugify#97]
Hello, first of all thank you very much for this plugin. 

I was starting a little project with nextjs and strapi **4.5.3** then i found [this video](https://www.youtube.com/watch?v=yMx3IXGI880) where the dev is using exactly what i need (find an article by his slug)

But when i did all the configuration (in the plugins.js file and then in the strapi admin with the findOne option for the permissions section) i got a **403** error from the api

What i'm doing wrong? i followed all the steps from the video and the plugin configuration and right now i'm stuck

**Comment by ComfortablyCoding** [comment]
I believe the permissions (for the role requesting the data) to check are

- you have the endpoint allowed
- you have the relevant content type find also allowed

If you have those two things it should work.

**Comment by ComfortablyCoding** [comment]
Closing due to no response, will re-open if any follow ups.
