### ISSUE TITLE
Strapi 4.11.4: Cannot find module '@strapi/utils/lib/errors'

### ISSUE THREAD

**Issue by JEliasLugo** [ComfortablyCoding/strapi-plugin-slugify#98]
Cannot find module '@strapi/utils/lib/errors'
Strapi 4.11.4 moved the sanitized and errors to "import { errors, sanitize } from '@strapi/utils';"

**Comment by kevinvugts** [comment]
I can confirm that @JEliasLugo identified this issue correctly! Strapi moved it to another package.

**Comment by plcdnl** [comment]
same issue. Is there a temporary solution ?

**Comment by maxostarr** [comment]
I am also having this issue. I've created a patched version as a workaround for now. 
https://www.npmjs.com/package/strapi-plugin-slugify-error-fix

**Comment by maxostarr** [comment]
#99 Fixes this issue.

**Comment by limpep** [comment]
Thanks, hopefully can get it in soon

**Comment by douwepausma** [comment]
If you need a quick fix until the new versions is released: `npm install ComfortablyCoding/strapi-plugin-slugify#pull/99/head`

**Comment by ComfortablyCoding** [comment]
This should be fixed in the latest releae (v2.3.3)
